### ISSUE TITLE
Crash in sample_environment_direction_pdf

### ISSUE THREAD

**Issue by guillaumechereau** [xelatihy/yocto-gl#393] opened 2019-03-20 08:15 UTC
The rendering thread sometimes crashes in the function sample_environment_direction_pdf.

It seems to happen when the texcoord variable gets a y value of exactly 1.0, in that case the idx overflows the elements_cdf size.

**Comment by xelatihy** [comment] 2019-03-20 09:09
Mmmm... that should not have happened. Let me look into it.

**Comment by xelatihy** [comment] 2019-03-20 09:15
I was not able to reproduce this bug. But I pushed a fix to master that should ensure that there are no overflows. I am closing this bug for now, but if it happens again we should reopen it.

ps: do you have any input files I could use as a test? You can create one save_scene().

**Closed by xelatihy** 2019-03-20 09:15 UTC
Labels: bug, next release

**Comment by guillaumechereau** [comment] 2019-03-20 09:25
I can reproduce it with yitrace, with the command:

    ./bin/yitrace -R780 --add-skyenv tests/basic-al.json

We can see that the rendering stops at the frame 210.

Not that there are no visible error messages.

![image](https://user-images.githubusercontent.com/107679/54673266-e393af00-4b34-11e9-9e7d-470259677d4b.png)

**Comment by guillaumechereau** [comment] 2019-03-20 09:34
Your commit seems to fix it.  But wouldn't clamping the random value introduce a slight bias in the rendering (albeit very small in that case) ?  Wouldn't something like:

    auto i    = (int)(texcoord.x * (size.x - 1));

be a better fix ?

**Comment by xelatihy** [comment] 2019-03-20 09:55
Two things:

1. it is really bad that there is no error message in outrace --- I have to add a logging window but I am deep into changes for scaling to large scenes
2. we make an assumption that envmaps are large, so anything we do at a pixel-like resolution is negligible error; this tends to be the case for the scene of interests in our projects; for this reasons, the small change in pdf is a small enough error that is negliegeable compared to all other sampling imprecisions

**Comment by xelatihy** [comment] 2019-03-20 09:56
In case you have some scenes from your tool that I can take a look at, I can give some feedback on how to best use Yocto in your case ...

**Comment by xelatihy** [comment] 2019-03-20 10:01
One more comment: texture coordinates are not well-defined between APIs and file formats. For example whether image value refer to pixel corners or pixel centers. We assume values are at pixel corners, which simplifies tiling. But in that case, texture coordinates without tiling should be defined in the [0,1) range not [0,1]. And here the fun begins with numerical precision problems and clamping with epsilons :-)

**Comment by guillaumechereau** [comment] 2019-03-20 10:20
OK thanks for the clarification.

I am currently evaluating using yocto for goxel (again) after having too much troubles with cycles.  You can check the test branch here if you are interested.
https://github.com/guillaumechereau/goxel/tree/yoctogl-test

It's just a playground branch that won't be merged so I haven't tried to have a clean git log on it.  At the moment the code is basically a copy of yitrace.

So far I am quite happy with yocto (compared to cycles).  The async api works perfectly, while I had a lot of threading issues at the time when I used cycles.  The only few problems I have are:

- It's quite slow to compile on linux (takes about 1m on my computer).  This make it quite tedious for me to dig into the code.
- I can't compile on iOS without having to add some hacks due to the fact that xcode doesn't support C++17 std lib yet.

On my wish list of things I might try to implement using yocto for goxel are:
- Bidirectional path tracing (with MIS), or other strategies that might help reduce the noise.  Only if that doesn't make the code too complicated, I value code simplicity over features.
- Support for disney principled brdf.

Thanks a lot for yocto.
