### ISSUE TITLE
example application build failed

### ISSUE THREAD

**Issue by ymb27** [xelatihy/yocto-gl#48] opened 2018-01-24 03:51 UTC
Aften I run the cmake .. with no problem. I run the cmake --build， it fail for the reason:

CMakeFiles/yocto_gl.dir/build.make:62: recipe for target 'CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o' failed
make[2]: *** [CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/yocto_gl.dir/all' failed
make[1]: *** [CMakeFiles/yocto_gl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

there are some error like 

error: converting to ‘std::tuple<std::vector<ygl::vec4i, std::allocator<ygl::vec4i> >, std::vector<ygl::vec3f, std::allocator<ygl::vec3f> >, std::vector<ygl::vec3f, std::allocator<ygl::vec3f> >, std::vector<ygl::vec2f, std::allocator<ygl::vec2f> > >’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...)

**Comment by xelatihy** [comment] 2018-01-25 06:58
Which os and compiler?

**Comment by xelatihy** [comment] 2018-02-06 11:49
I am closing this since I cannot reproduce it.

**Closed by xelatihy** 2018-02-06 11:49 UTC

**Comment by nmpribeiro** [comment] 2018-03-18 10:03
Hi, I am able to reproduce:
```
tests/gltf/yocto-gl/yocto/yocto_gl.cpp:12625:53: error: ‘class std::unordered_map<ygl::material_type, int>’ has no member named ‘at’
     set_program_uniform(prog.prog, mtype_id, mtypes.at(type));
                                                     ^
CMakeFiles/yocto_gl.dir/build.make:62: recipe for target 'CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o' failed
make[2]: *** [CMakeFiles/yocto_gl.dir/yocto/yocto_gl.cpp.o] Error 1
CMakeFiles/Makefile2:178: recipe for target 'CMakeFiles/yocto_gl.dir/all' failed
make[1]: *** [CMakeFiles/yocto_gl.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

OS: Linux Ubuntu 16.04
Compiler (I think...): gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)
```
